<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>grammar</string>
	</array>
	<key>name</key>
	<string>Instaparse</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?=\(\*)</string>
			<key>end</key>
			<string>(?&lt;=\*\))</string>
			<key>name</key>
			<string>comment.block.instaparse</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>empty token</string>
			<key>match</key>
			<string>\b(Epsilon|epsilon|EPSILON|eps|ε)\b</string>
			<key>name</key>
			<string>keyword.command.instaparse</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>comment</key>
			<string>Single quoted strings or characters</string>
			<key>end</key>
			<string>(?&lt;=[^\\])'|(?&lt;=[^\\])\\\\'|[\\]{4}'</string>
			<key>name</key>
			<string>string.quoted.single.single-line.instaparse</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>Double quoted strings or characters</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.double-line.instaparse</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>empty token</string>
			<key>match</key>
			<string>\(|\)|\{|\}|\*|\+|\?</string>
			<key>name</key>
			<string>entity.other.attribute-name.instaparse</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>peg expression</string>
			<key>match</key>
			<string>&amp;|!|/</string>
			<key>name</key>
			<string>constant.language.instaparse</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;(\w+)&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.twig.instaparse</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(:|\=|:\=|::\=)\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.instaparse</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;'</string>
			<key>comment</key>
			<string>hidden rule or token</string>
			<key>end</key>
			<string>'&gt;</string>
			<key>name</key>
			<string>string.quoted.single.single-line.instaparse</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;</string>
			<key>comment</key>
			<string>hidden rule or token</string>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>keyword.control.twig.instaparse</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([\w\-%@]+)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.class.instaparse</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>rule definition &amp; assignment token</string>
			<key>end</key>
			<string>(:|\=|:\=|::\=)\s</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.instaparse</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>rule name</string>
			<key>match</key>
			<string>\b(\w+)\b</string>
			<key>name</key>
			<string>variable.instaparse</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>alternation and rule ending</string>
			<key>match</key>
			<string>(\|)|;|\.</string>
			<key>name</key>
			<string>keyword.operator.instaparse</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Regex operators</string>
			<key>match</key>
			<string>\#</string>
			<key>name</key>
			<string>variable.parameter.instaparse</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Section definitions like @header</string>
			<key>match</key>
			<string>^\s*(?:@)([a-z]+)\b</string>
			<key>name</key>
			<string>storage.type.function.instaparse</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.instaparse</string>
	<key>uuid</key>
	<string>8da3e770-b1cc-11e2-9e96-0800200c9a66</string>
</dict>
</plist>
